pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        stage('Deploy in staging Env'){
            build job: 'Deploy_Application_Staging_Env'
            }
        }
        stage('Deploy to Prodaction'){
            steps{
                timeout(time:5, unit:'DAYS'){
                    input message:'approve PROD deploy'
                }
                build job: 'Deploy_Application_PROD_Env'
            }
        }
    }
}